name: Create Deployment Branch
on:
  workflow_dispatch:
    inputs:
      GIT_TAG:
        required: true
        description: 'Tag to create on'

permissions:
  contents: write
  pull-requests: write
  packages: write   
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clean workspace
      shell: bash
      run: rm -rf ${{ github.workspace }}/*

    - name: Checkout
      uses: actions/checkout@v4.1.0
      with:  
        ref: ${{ inputs.GIT_TAG }}

    - name: Git Pull
      run: git pull
    
    # ignore the previous failure if it exists
    - name: Create Head Branch
      id: create-head-branch
      if: always() 
      shell: bash
      run: |- 
        git checkout -b head-branch-${{ inputs.GIT_TAG }}
        git checkout ${{ inputs.GIT_TAG }}
        git push --set-upstream origin head-branch-${{ inputs.GIT_TAG }}