name: Deploy To Prod
run-name: Deploy To Prod - ${{ inputs.GIT_TAG }}
on:
  workflow_dispatch:
    inputs:
      GIT_TAG:
        required: true
        description: 'Tag to create on'

permissions:
  contents: write
  pull-requests: write
  packages: write   
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clean workspace
      shell: bash
      run: rm -rf ${{ github.workspace }}/*

    - name: Checkout
      uses: actions/checkout@v4.1.0
      with:  
        fetch-depth: 0 # this fetch depth 0 is required to "fetch all history for all branches and tags"
    
    - name: Check that a pull request was made
      shell: bash
      run: |- 
        echo "::error::foobar" && exit 1
      env:
        GH_TOKEN: ${{ github.token }}